-- Initial Users Setup for Web Work Request Application
-- Run this script after creating the database tables
-- Replace the password hashes with actual hashes generated by the password tool

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create initial admin/operator user
INSERT INTO users (
    id,
    username,
    password_hash,
    name,
    email,
    unit,
    role,
    created_at,
    updated_at
) VALUES (
    uuid_generate_v4(),
    'admin',
    '$2a$10$YOUR_HASH_HERE', -- Replace with actual hash from password tool
    'Administrator',
    'admin@example.com',
    'IT Department',
    'operator',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

-- Create initial regular user
INSERT INTO users (
    id,
    username,
    password_hash,
    name,
    email,
    unit,
    role,
    created_at,
    updated_at
) VALUES (
    uuid_generate_v4(),
    'user1',
    '$2a$10$YOUR_HASH_HERE', -- Replace with actual hash from password tool
    'Regular User',
    'user1@example.com',
    'General Department',
    'user',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

-- Create test user for development
INSERT INTO users (
    id,
    username,
    password_hash,
    name,
    email,
    unit,
    role,
    created_at,
    updated_at
) VALUES (
    uuid_generate_v4(),
    'testuser',
    '$2a$10$YOUR_HASH_HERE', -- Replace with actual hash from password tool
    'Test User',
    'test@example.com',
    'Test Department',
    'user',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

-- Verify the users were created
SELECT 
    username,
    name,
    email,
    unit,
    role,
    created_at
FROM users
ORDER BY created_at;
